version: 1.0
clean:
  excludeDir:
    - node_modules
  # excludeFile:
  #   - app.js
generate:
  - description: Create a hello-world nodeJS API application
    templateUrl: https://api.snapdevhub.com/m/snapdev/nodejs-api/hello-world
    # version: latest # default
    # root: true
    