name: Build, test, and deploy

on:
  # workflow_dispatch:
  # pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:

      - name: Pushbullet Notification
        uses: ShaunLWM/action-pushbullet@master
        env:
          PB_TOKEN: ${{ secrets.PB_TOKEN }}
          PB_TITLE: snapdev-cli
          PB_TEXT: "Build job started"

      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Pushbullet Notification
        uses: ShaunLWM/action-pushbullet@master
        env:
          PB_TOKEN: ${{ secrets.PB_TOKEN }}
          PB_TITLE: snapdev-cli
          PB_TEXT: "Installing dependencies"

      # Install node dependencies
      - name: "Setup Node.js"
        uses: actions/setup-node@v1
        with:
          node-version: '12'
          registry-url: https://registry.npmjs.org/

      # https://github.com/marketplace/actions/github-action-for-yarn
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Pushbullet Notification
        uses: ShaunLWM/action-pushbullet@master
        env:
          PB_TOKEN: ${{ secrets.PB_TOKEN }}
          PB_TITLE: snapdev-cli
          PB_TEXT: "Tagging the branch"

      # tag the branch
      - name: Bump version and push tag
        id: bump
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          DEFAULT_BUMP: patch

      - run: npm --no-git-tag-version --allow-same-version version ${{ steps.bump.outputs.tag }}

      - name: Pushbullet Notification
        uses: ShaunLWM/action-pushbullet@master
        env:
          PB_TOKEN: ${{ secrets.PB_TOKEN }}
          PB_TITLE: snapdev-cli
          PB_TEXT: "Publish to NPM"

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Pushbullet Notification
        uses: ShaunLWM/action-pushbullet@master
        env:
          PB_TOKEN: ${{ secrets.PB_TOKEN }}
          PB_TITLE: snapdev-cli
          PB_TEXT: "Build job completed"

